name: Beispiel-Pipeline

on:
  push:
    branches:
      - main

stages:
  - name: Vorbereitung
    jobs:
      - name: Checkout-Code
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

  - name: Build
    jobs:
      - name: Node.js-Build
        runs-on: ubuntu-latest
        steps:
          - name: Verwende Node.js 14.x
            uses: actions/setup-node@v2
            with:
              node-version: 14.x

          - name: Installiere Abhängigkeiten
            run: npm ci

          - name: Baue die Anwendung
            run: npm build

  - name: Test
    jobs:
      - name: Unit-Tests
        runs-on: ubuntu-latest
        steps:
          - name: Verwende Node.js 14.x
            uses: actions/setup-node@v2
            with:
              node-version: 14.x

          - name: Installiere Abhängigkeiten
            run: npm ci

          - name: Führe Tests aus
            run: npm test

  - name: Bereitstellung
    jobs:
      - name: Deployment
        runs-on: ubuntu-latest
        steps:
          - name: Deployment-Schritte hier

